# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
  #    - /gitlab-templates/reuse-lint.yml
      # - /gitlab-templates/linux-qt6.yml # no libaccounts-qt and friends in CI yet
      # - /gitlab-templates/freebsd-qt6.yml
