# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcmutils': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/kwallet': '@stable'
    'frameworks/kio': '@stable'
    'third-party/qcoro': '@latest'
    'third-party/libaccounts-qt': '@latest'
    'third-party/signond': '@latest'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/kwallet': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'third-party/qcoro': '@latest'
    'third-party/libaccounts-qt': '@latest'
    'third-party/signond': '@latest'
