# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcmutils': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/kwallet': '@stable'
    'frameworks/kio': '@stable'
    'third-party/qcoro': '@latest'
    'third-party/libaccounts-qt': '@latest'
    'third-party/signond': '@latest'

Options:
  cmake-options: "-DKF6_COMPAT_BUILD=ON" # This is for the Qt5 build. Revisit this once we have a working Qt6 build and only enable for Qt5
